In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))



In [4]:
data = np.random.randn(2, 3)
data
data * 10
data + data

array([[-1.40331187,  2.28524942,  0.36210786],
       [ 4.03131875, -0.8019344 ,  1.71068717]])

In [13]:
data.shape
data.dtype
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2
arr2.ndim
arr2.shape
np.zeros(10)
np.empty((2, 3, 2))
np.arange(15)
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype




dtype('int32')

In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

## Arithmetic

In [23]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr
arr - arr
1 / arr
arr ** 0.5
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr



array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [38]:
arr = np.arange(10)
arr[5]
arr[5:8]
arr[5:8] = 12
arr
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr
arr_slice[:] = 64
arr
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
arr2d[0][2]
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
arr3d[0]
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d
arr3d[1, 0]
x = arr3d[1]
x[0]

array([7, 8, 9])

In [41]:
arr
arr[1:6]
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2, 1:]
arr2d[:2, 2] #[:rows, :columns]
arr2d[:, :1]
arr2d[:2, 1:] = 0


## Boolean Indexing

In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data
#names == 'Bob'

array([[-0.09922986, -1.21007012,  0.82794876,  1.36924027],
       [-1.31680988,  1.2683386 , -0.38849845,  0.11357595],
       [ 1.6123514 ,  0.44558501, -0.85849572, -1.21212372],
       [ 0.51163233,  1.24819908, -0.58680766, -0.69651307],
       [ 0.84729318,  2.06881339,  0.60853419,  0.79476478],
       [-0.16681186,  0.56333823,  0.07740167, -0.41595863],
       [-2.17973136,  1.91306997, -1.73399348, -1.00441455]])

In [57]:
data[names == 'Bob']

array([[-0.09922986, -1.21007012,  0.82794876,  1.36924027],
       [ 0.51163233,  1.24819908, -0.58680766, -0.69651307]])

In [58]:
data[names == 'Bob', 2:]

array([[ 0.82794876,  1.36924027],
       [-0.58680766, -0.69651307]])

In [52]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [53]:
data[~(names == 'Bob')]

array([[ 1.59906123,  0.01008036, -0.57370663,  0.83289401],
       [-1.44805609, -1.10810338, -0.62437346,  1.66236817],
       [ 0.17991681, -1.61986204, -0.33057855, -1.00178724],
       [-1.31471067,  0.55701176, -0.01973799, -1.27123128],
       [ 0.97789405,  1.42149103, -1.19647735,  0.32765052]])

In [60]:
cond = names == 'Bob'
data[~cond]


array([[-1.31680988,  1.2683386 , -0.38849845,  0.11357595],
       [ 1.6123514 ,  0.44558501, -0.85849572, -1.21212372],
       [ 0.84729318,  2.06881339,  0.60853419,  0.79476478],
       [-0.16681186,  0.56333823,  0.07740167, -0.41595863],
       [-2.17973136,  1.91306997, -1.73399348, -1.00441455]])

In [61]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [64]:
data[mask]
data[data < 0] = 0
data

array([[0.        , 0.        , 0.82794876, 1.36924027],
       [0.        , 1.2683386 , 0.        , 0.11357595],
       [1.6123514 , 0.44558501, 0.        , 0.        ],
       [0.51163233, 1.24819908, 0.        , 0.        ],
       [0.84729318, 2.06881339, 0.60853419, 0.79476478],
       [0.        , 0.56333823, 0.07740167, 0.        ],
       [0.        , 1.91306997, 0.        , 0.        ]])

In [65]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.2683386 , 0.        , 0.11357595],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.56333823, 0.07740167, 0.        ],
       [0.        , 1.91306997, 0.        , 0.        ]])

## Fancy Indexing

In [69]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [70]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [71]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [72]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [73]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [74]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [76]:
arr = np.random.randn(6, 3)
arr

array([[-0.83650082, -1.38251668,  0.58057877],
       [-1.09066856,  1.12135153, -0.42818822],
       [-1.09285584,  0.05312082,  0.5860566 ],
       [ 0.54746466, -0.15692299, -0.95036483],
       [ 1.61580468, -0.95259106,  0.23441476],
       [-0.34098256, -0.28252381,  0.00634398]])

In [77]:
np.dot(arr.T, arr)

array([[ 6.11043682, -1.6533751 , -0.80280444],
       [-1.6533751 ,  4.18347767, -1.32763719],
       [-0.80280444, -1.32763719,  1.82206304]])

In [78]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [80]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [81]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])